version: "3.7"
services:
  mysql:
    image: mysql:8.0-debian
    container_name: mysql-db
    ports:
      - 3306:3306
    volumes:
      - ./db/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    networks:
      - nestjs-network
  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - nestjs-network

networks:
  nestjs-network:
    driver: bridge
